installer:
  image: andreaskoch/dockerized-magento-installer
  environment:
    DOMAIN: dockerized-magento.local
    MAGENTO_ROOT: /var/www/html/web
    MYSQL_HOST: mysql
    MYSQL_DATABASE: magento
    MYSQL_USER: root
    MYSQL_PASSWORD: pw
    ADMIN_USERNAME: admin
    ADMIN_FIRSTNAME: Admin
    ADMIN_LASTNAME: Inistrator
    ADMIN_PASSWORD: password123
    ADMIN_FRONTNAME: admin
    ADMIN_EMAIL: admin@example.com
    ENCRYPTIONKEY: 731aea833710535779fe8c7c49bc6c4d
  volumes_from:
    - nginx
  volumes:
    - ./config/installer/php/php.ini:/usr/local/etc/php/php.ini
    - ./config/installer/magerun/n98-magerun.yaml.tmpl:/etc/n98-magerun.yaml.tmpl
    - ./config/installer/magento/local.xml.tmpl:/etc/local.xml.tmpl
    - ./config/installer/magento/fpc.xml.tmpl:/etc/fpc.xml.tmpl
    - ./config/installer/bin/substitute-env-vars.sh:/bin/substitute-env-vars.sh
    - ./config/installer/bin/install.sh:/bin/install.sh
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "mysql:mysql"
  entrypoint: /bin/install.sh

nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes:
    - ./logs/nginx:/var/log/nginx
    - ./config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
    - ./config/ssl/cert.key:/etc/nginx/ssl/cert.key
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
    - ./config/nginx/includes:/etc/nginx/includes
    - ./config/nginx/custom-locations:/etc/nginx/custom-locations
  volumes_from:
    - php
php:
  image: andreaskoch/dockerized-magento-php
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "mysql:mysql"
    - "elasticsearch:elasticsearch"
  volumes:
    - .:/var/www/html
mysql:
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: pw
  volumes:
    - ./data/mysql:/var/lib/mysql
cache:
  image: redis:latest
sessions:
  image: redis:latest
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:80"
  links:
    - "mysql:mysql"
  environment:
    PMA_HOST: "mysql"
    PMA_PORT: 3306
elasticsearch:
  build: ./elastic-magento
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  mem_limit: 1g
  volumes:
    - esdata1:/usr/share/elasticsearch/data
  ports:
    - 9200:9200
logstash:
  build: ./logstash-magento
  ports:
    - "5000:5000"
  environment:
    LS_JAVA_OPTS: "-Xmx512m -Xms512m"
  links:
    - "elasticsearch:elasticsearch"
  volumes_from:
    - logdata

apache:
  build: ./apache-magento-tracker
  volumes_from: 
    - logdata
  ports:
    - "801:80"
  environment:
    - DOMAIN=t.ph.com:801

logdata:
  image: tianon/true
  volumes:
    - /var/log/smile_searchandising_suite/apache_raw_events
    - /var/log/apache2installer:
  image: andreaskoch/dockerized-magento-installer
  environment:
    DOMAIN: dockerized-magento.local
    MAGENTO_ROOT: /var/www/html/web
    MYSQL_HOST: mysql
    MYSQL_DATABASE: magento
    MYSQL_USER: root
    MYSQL_PASSWORD: pw
    ADMIN_USERNAME: admin
    ADMIN_FIRSTNAME: Admin
    ADMIN_LASTNAME: Inistrator
    ADMIN_PASSWORD: password123
    ADMIN_FRONTNAME: admin
    ADMIN_EMAIL: admin@example.com
    ENCRYPTIONKEY: 731aea833710535779fe8c7c49bc6c4d
  volumes_from:
    - nginx
  volumes:
    - ./config/installer/php/php.ini:/usr/local/etc/php/php.ini
    - ./config/installer/magerun/n98-magerun.yaml.tmpl:/etc/n98-magerun.yaml.tmpl
    - ./config/installer/magento/local.xml.tmpl:/etc/local.xml.tmpl
    - ./config/installer/magento/fpc.xml.tmpl:/etc/fpc.xml.tmpl
    - ./config/installer/bin/substitute-env-vars.sh:/bin/substitute-env-vars.sh
    - ./config/installer/bin/install.sh:/bin/install.sh
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "fullpagecache:redisfullpagecache"
    - "mysql:mysql"
  entrypoint: /bin/install.sh

nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes:
    - ./logs/nginx:/var/log/nginx
    - ./config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
    - ./config/ssl/cert.key:/etc/nginx/ssl/cert.key
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf
    - ./config/nginx/includes:/etc/nginx/includes
    - ./config/nginx/custom-locations:/etc/nginx/custom-locations
  volumes_from:
    - php
php:
  image: andreaskoch/dockerized-magento-php
  links:
    - "cache:rediscache"
    - "sessions:redissession"
    - "mysql:mysql"
    - "elasticsearch:elasticsearch"
  volumes:
    - .:/var/www/html
mysql:
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: pw
  volumes:
    - ./data/mysql:/var/lib/mysql
cache:
  image: redis:latest
sessions:
  image: redis:latest
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:80"
  links:
    - "mysql:mysql"
  environment:
    PMA_HOST: "mysql"
    PMA_PORT: 3306
elasticsearch:
  build: ./elastic-magento
  environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  mem_limit: 1g
  volumes:
    - esdata1:/usr/share/elasticsearch/data
  ports:
    - 9200:9200
logstash:
  build: ./logstash-magento
  ports:
    - "5000:5000"
  environment:
    LS_JAVA_OPTS: "-Xmx512m -Xms512m"
  links:
    - "elasticsearch:elasticsearch"
  volumes_from:
    - logdata

apache:
  build: ./apache-magento-tracker
  volumes_from: 
    - logdata
  ports:
    - "801:80"
  environment:
    - DOMAIN=t.ph.com:801

logdata:
  image: tianon/true
  volumes:
    - /var/log/smile_searchandising_suite/apache_raw_events
    - /var/log/apache2
